{
 "title": "Application - Dubbo Monitoring - K8S",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "khulnasoft-khulnasoft-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "service",
    "label": "Dubbo Service",
    "query": {}
   },
   {
    "name": "observation_point",
    "label": "Tap Side",
    "query": {}
   },
   { "name": "khulnasoft_tracing_id", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a352df35-1007-c942-c587-c748170530fd\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"aff8f4fc-a103-a81c-40b1-6d324a8ff23d\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"1fdcb042-495b-7574-ca4f-727069af0d1e\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5a6e4cfa-6be2-4eaa-24f8-59bb581e4f23\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"25528255-95d7-1360-8b1f-0ae5ecc7d611\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"1ae892e8-55cc-2e8e-eace-388498e9ed6b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0a3bf855-6fda-cf52-dc8a-899a990cda21\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"304ffc5d-3655-8156-ec6c-dd949ca10aa8\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8ee333ff-5f3e-111e-5072-261e5d9bf72a\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(request)", "name": "Sum(request)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_id_1",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_1",
       "role": "server"
      }
     ],
     "sql": "SELECT Sum(`request`) AS `Sum(request)`, time(time, 60) AS `time_60`, node_type(region_1) AS `server_node_type`, icon_id(region_1) AS `server_icon_id`, region_id_1, region_1 FROM application_map WHERE pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND pod_ns_1 = 'dubbo-application' AND auto_service_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, region_1, region_id_1, `server_node_type` SLIMIT 20 LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f3a5a790-c302-f118-f4ba-ee7f6b1dc3b2\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"1bd631b0-4db7-fad5-eec4-0041e496949d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Avg(client_error_ratio)", "name": "Avg(client_error_ratio)", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_id_1",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_1",
       "role": "server"
      }
     ],
     "sql": "SELECT Avg(`client_error_ratio`) AS `Avg(client_error_ratio)`, node_type(region_1) AS `server_node_type`, icon_id(region_1) AS `server_icon_id`, region_id_1, region_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_ns_1 = 'dubbo-application' AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY region_1, region_id_1, `server_node_type` LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0da00259-9e89-b867-f636-0e026ba5cd55\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"f5faa05a-a229-be81-a651-8219d776d88c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Avg(server_error_ratio)", "name": "Avg(server_error_ratio)", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_id_1",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_1",
       "role": "server"
      }
     ],
     "sql": "SELECT Avg(`server_error_ratio`) AS `Avg(server_error_ratio)`, time(time, 60) AS `time_60`, node_type(region_1) AS `server_node_type`, icon_id(region_1) AS `server_icon_id`, region_id_1, region_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_ns_1 = 'dubbo-application' AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, region_1, region_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
    }
   ]
  },
  {
   "title": "Dubbo Service Topo",
   "type": "khulnasoft-topo-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "metaExtra": {
      "common": [
       "observation_point",
       "Enum(observation_point)"
      ],
      "from": [ "auto_service_id_0" ],
      "to": [ "auto_service_id_1" ]
     },
     "queryText": "{\"appType\":\"accessRelationship\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"request_rate\",\"params\":[],\"uuid\":\"9d4505cc-8274-23f8-22f7-fb2006d0d0b3\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}},{\"type\":\"metric\",\"key\":\"rrt\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"delay_avg\",\"params\":[],\"uuid\":\"513bbd90-971c-2b7a-4908-06f27e944593\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"delay_max\",\"params\":[],\"uuid\":\"8e5e8400-3f7d-30a2-35ce-669f55824c74\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"server_error_sum\",\"params\":[],\"uuid\":\"3d5f8273-052e-ffa4-cbbd-357807bab760\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"timeout\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"time_out\",\"params\":[],\"uuid\":\"da39d8e3-23c9-aa37-e9ba-bf8684d4d9df\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"eb0143cd-5999-d802-9d67-df5ece4c72f6\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"97ad3d8f-d2b9-75be-cb2e-44f1269a891f\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"58f11594-d61b-b6b1-5951-26da37367400\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"ddc31223-4fff-c31c-dcf9-7284993d88db\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"756a1bdb-c70e-6e6f-cfeb-f183bc378008\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"71b8d05e-f108-5be4-e592-7cc66559963e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"from\"},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4ea80059-5d63-1914-b948-e3ef51fc4927\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c789c720-e6a5-d87f-a929-0b889724ac94\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b2f6bebe-15ee-14f3-888d-945414181cf0\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "request_rate", "name": "request_rate", "type": 1, "unit": "/s" },
      { "displayName": "delay_avg", "name": "delay_avg", "type": 3, "unit": "us" },
      { "displayName": "delay_max", "name": "delay_max", "type": 3, "unit": "us" },
      { "displayName": "server_error_sum", "name": "server_error_sum", "type": 1, "unit": "" },
      { "displayName": "time_out", "name": "time_out", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`client_node_type`",
       "role": "client"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`client_icon_id`",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_0",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_0",
       "role": "client"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "TAP Side",
       "isResource": false,
       "name": "Enum(observation_point)"
      },
      {
       "displayName": "TAP Side",
       "isResource": false,
       "name": "observation_point"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `request_rate`, Avg(`rrt`) AS `delay_avg`, Max(`rrt_max`) AS `delay_max`, Sum(`server_error`) AS `server_error_sum`, Avg(`timeout`) AS `time_out`, node_type(auto_service_0) AS `client_node_type`, icon_id(auto_service_0) AS `client_icon_id`, auto_service_id_0, auto_service_0, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1, Enum(observation_point), observation_point FROM application_map WHERE auto_service_id_1!=0 AND pod_ns_id_1!=0 AND pod_cluster_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_service_0, auto_service_1, observation_point, auto_service_id_0, auto_service_id_1, `client_node_type`, `server_node_type` LIMIT 1000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"fe16ca5b-2878-3d3e-22db-d5891f2de731\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"66e3b5a8-c0e0-38ee-c885-6c04b4e1184f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(client_error)", "name": "Sum(client_error)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_id_1",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_1",
       "role": "server"
      }
     ],
     "sql": "SELECT Sum(`client_error`) AS `Sum(client_error)`, time(time, 60) AS `time_60`, node_type(region_1) AS `server_node_type`, icon_id(region_1) AS `server_icon_id`, region_id_1, region_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_ns_1 = 'dubbo-application' AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, region_1, region_id_1, `server_node_type` SLIMIT 20 LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4e669b21-a80e-3e57-c949-13b057d98ff5\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"8a86b61d-c9dd-180c-b6fa-07bfc277b77d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(server_error)", "name": "Sum(server_error)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_id_1",
       "role": "server"
      },
      {
       "displayName": "Region",
       "isResource": true,
       "name": "region_1",
       "role": "server"
      }
     ],
     "sql": "SELECT Sum(`server_error`) AS `Sum(server_error)`, time(time, 60) AS `time_60`, node_type(region_1) AS `server_node_type`, icon_id(region_1) AS `server_icon_id`, region_id_1, region_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_ns_1 = 'dubbo-application' AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, region_1, region_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
    }
   ]
  },
  {
   "title": "Network Delay (by Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"network\",\"select\":[{\"key\":\"rtt\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"TCP Round Trip Duration\",\"params\":[],\"uuid\":\"016e679f-c755-d931-7748-0f644d82b4ba\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"art\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Data Transfer Duration\",\"params\":[],\"uuid\":\"dea1be27-f952-3532-67b3-dd01cc9cf80c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"rrt\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"App Duration\",\"params\":[],\"uuid\":\"0dae4bb6-330b-4f3d-b9bb-1224d70c498b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3868cec7-28d4-efa6-e9f5-ffce2c5f545c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4da814ec-4a05-f26e-06b6-39345acb0dce\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f43241d2-a04b-971e-47ac-16719272a533\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"fad9d4fc-ec16-66de-fa61-faeded5833de\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f99c47b0-0f32-39c2-4fee-b0f1c56453f3\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"322d39d9-96fc-f193-0f8f-c09b398b15b3\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${pod_cluster}-Cluster\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "TCP Round Trip Duration", "name": "TCP Round Trip Duration", "type": 3, "unit": "us" },
      { "displayName": "Data Transfer Duration", "name": "Data Transfer Duration", "type": 3, "unit": "us" },
      { "displayName": "App Duration", "name": "App Duration", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": false,
       "name": "`node_type`"
      },
      {
       "displayName": "图标",
       "isResource": false,
       "name": "`icon_id`"
      },
      {
       "displayName": "K8s Cluster",
       "isResource": false,
       "name": "pod_cluster_id"
      },
      {
       "displayName": "K8s Cluster",
       "isResource": false,
       "name": "pod_cluster"
      }
     ],
     "sql": "SELECT Avg(`rtt`) AS `TCP Round Trip Duration`, Avg(`art`) AS `Data Transfer Duration`, Avg(`rrt`) AS `App Duration`, time(time, 60) AS `time_60`, node_type(pod_cluster) AS `node_type`, icon_id(pod_cluster) AS `icon_id`, pod_cluster_id, pod_cluster FROM network WHERE pod_cluster_id!=0 AND pod_ns_id!=0 AND auto_service_id!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, pod_cluster, pod_cluster_id, `node_type` SLIMIT 20 LIMIT 100"
    }
   ]
  },
  {
   "title": "Dubbo Service Delay",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7998acf4-9c0c-05bb-f070-f85cefecdb15\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"metric\",\"key\":\"request\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"Request Sum\",\"params\":[],\"uuid\":\"b9384b44-4e10-d160-0a0a-f3fa0f521ddd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Delay Avg\",\"params\":[],\"uuid\":\"05e6eeee-c040-41ff-9275-fea7a943b5aa\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"Delay P75\",\"params\":[\"75\"],\"uuid\":\"85eb556e-ffaf-b183-2c98-0a9cfab4e09b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"75\"]}},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"Delay P90\",\"params\":[\"90\"],\"uuid\":\"3ca3a29b-11b4-5d3b-49f6-b3d5f4016250\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"Delay P99\",\"params\":[\"99\"],\"uuid\":\"d0905664-24b2-9f2b-4ada-9428aed9760d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"99\"]}},{\"type\":\"metric\",\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Client Error Ratio\",\"params\":[],\"uuid\":\"d9bf8491-fe0b-e8a6-ae13-ead1c7b96bb5\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Server Error Ratio\",\"params\":[],\"uuid\":\"7b143d95-1ca9-3717-3ae8-df16b7dd809d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"type\":\"tag\",\"key\":\"auto_service\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"918876ae-284e-c8ce-be69-8cea5dd72a60\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"a0c72ce0-569e-b014-d029-145a186c158a\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bcfbbcf4-3699-b4d6-18a9-b28022c9e273\",\"subFuncs\":[],\"whereOnly\":true,\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"2941f9a3-eca8-c424-a250-c8956fa49c63\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"08179997-0cde-9243-0d50-153f8ba0fbd8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"241f1aaa-bfff-b64b-e558-dea1ba03c07b\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9c372fbf-a662-d958-d2b6-27d1ecee0e76\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"83b6e474-4cbc-5ee3-b3c1-ef149c2b9091\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Request Sum", "name": "Request Sum", "type": 1, "unit": "" },
      { "displayName": "Delay Avg", "name": "Delay Avg", "type": 3, "unit": "us" },
      { "displayName": "Delay P75", "name": "Delay P75", "type": 3, "unit": "us" },
      { "displayName": "Delay P90", "name": "Delay P90", "type": 3, "unit": "us" },
      { "displayName": "Delay P99", "name": "Delay P99", "type": 3, "unit": "us" },
      { "displayName": "Client Error Ratio", "name": "Client Error Ratio", "type": 4, "unit": "%" },
      { "displayName": "Server Error Ratio", "name": "Server Error Ratio", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      }
     ],
     "sql": "SELECT Sum(`request`) AS `Request Sum`, Avg(`response_duration`) AS `Delay Avg`, Percentile(`response_duration`,0.75) AS `Delay P75`, Percentile(`response_duration`,0.9) AS `Delay P90`, Percentile(`response_duration`,0.99) AS `Delay P99`, Avg(`client_error_ratio`) AS `Client Error Ratio`, Avg(`server_error_ratio`) AS `Server Error Ratio`, auto_service_1, auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id` FROM l7_flow_log WHERE (auto_service_id_0!=0 OR auto_service_id_1!=0) AND (pod_ns_id_0!=0 OR pod_ns_id_1!=0) AND (pod_cluster_id_0!=0 OR pod_cluster_id_1!=0) AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_service_1, auto_service_id_1, `server_node_type` LIMIT 1000"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"e69c8676-330c-9e52-31cc-a05f07d1bc56\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4997090a-952d-fc30-baab-1c14910f8ca8\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3b402395-c288-8ea5-936c-47486ad2aac5\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"79e2276e-de17-d85f-96e9-c3c466363df9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "PerSecond(Avg(request))", "name": "PerSecond(Avg(request))", "type": 1, "unit": "/s" }
       ],
       "returnTags": [
        {
         "displayName": "time_60",
         "isResource": false,
         "name": "`time_60`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(request))`, time(time, 60) AS `time_60`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE l7_protocol IN (40) AND pod_ns_id_1!=0 AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, auto_instance_0, auto_instance_id_0, `client_node_type` SLIMIT 20 LIMIT 1000"
      }
     ]
    },
    {
     "title": "Request (by Consumer)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"request\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4997090a-952d-fc30-baab-1c14910f8ca8\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"658171c6-b6f4-9611-386a-49ecc446b77e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b00330ff-f4c9-720a-18c0-34ec67a79f9e\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"79e2276e-de17-d85f-96e9-c3c466363df9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "request", "name": "request", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT Sum(`request`) AS `request`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE l7_protocol IN (40) AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND pod_ns_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_instance_0, auto_instance_id_0, `client_node_type` LIMIT 10"
      }
     ]
    },
    {
     "title": "Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"response\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"response\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"e69c8676-330c-9e52-31cc-a05f07d1bc56\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4997090a-952d-fc30-baab-1c14910f8ca8\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3b402395-c288-8ea5-936c-47486ad2aac5\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"79e2276e-de17-d85f-96e9-c3c466363df9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "response", "name": "response", "type": 1, "unit": "/s" }
       ],
       "returnTags": [
        {
         "displayName": "time_60",
         "isResource": false,
         "name": "`time_60`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`server_node_type`",
         "role": "server"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`server_icon_id`",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_id_1",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_1",
         "role": "server"
        }
       ],
       "sql": "SELECT PerSecond(Avg(`response`)) AS `response`, time(time, 60) AS `time_60`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM application_map WHERE l7_protocol IN (40) AND pod_ns_id_1!=0 AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, auto_service_1, auto_service_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
      }
     ]
    },
    {
     "title": "Response (by Provider)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"response\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"response\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4997090a-952d-fc30-baab-1c14910f8ca8\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"658171c6-b6f4-9611-386a-49ecc446b77e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b00330ff-f4c9-720a-18c0-34ec67a79f9e\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"79e2276e-de17-d85f-96e9-c3c466363df9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "response", "name": "response", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`server_node_type`",
         "role": "server"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`server_icon_id`",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_id_1",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_1",
         "role": "server"
        }
       ],
       "sql": "SELECT Sum(`response`) AS `response`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM application_map WHERE l7_protocol IN (40) AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND pod_ns_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_service_1, auto_service_id_1, `server_node_type` LIMIT 10"
      }
     ]
    }
   ]
  },
  {
   "title": "Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delay (by Provider)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P90\",\"params\":[\"90\"],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"cbe69eb3-ac42-92fd-ab7d-5ff3e5248d80\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"853765fd-debf-b6cd-5b58-d35daa63d360\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"615e7058-d207-3a28-4d93-479eac66a8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"38fde680-7393-b962-68b3-d109da931afd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} P90\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "P90", "name": "P90", "type": 3, "unit": "us" }
       ],
       "returnTags": [
        {
         "displayName": "time_1",
         "isResource": false,
         "name": "`time_1`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`server_node_type`",
         "role": "server"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`server_icon_id`",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_id_1",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_1",
         "role": "server"
        }
       ],
       "sql": "SELECT Percentile(`rrt`,0.9) AS `P90`, time(time, 1) AS `time_1`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_cluster_id_1!=0 AND pod_ns_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_1`, auto_service_1, auto_service_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
      },
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P95\",\"params\":[\"95\"],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"95\"]}}],\"where\":[{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"cbe69eb3-ac42-92fd-ab7d-5ff3e5248d80\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9486053e-bfd8-1cb0-8230-39225d23376a\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7ce067f3-0aca-17ab-7a0c-5832110425f5\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"615e7058-d207-3a28-4d93-479eac66a8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"47c03c4c-b34f-af7d-d8f9-c52a42ab5a3e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} P95\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "P95", "name": "P95", "type": 3, "unit": "us" }
       ],
       "returnTags": [
        {
         "displayName": "time_1",
         "isResource": false,
         "name": "`time_1`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`server_node_type`",
         "role": "server"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`server_icon_id`",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_id_1",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_1",
         "role": "server"
        }
       ],
       "sql": "SELECT Percentile(`rrt`,0.95) AS `P95`, time(time, 1) AS `time_1`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM application_map WHERE pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND pod_ns_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_1`, auto_service_1, auto_service_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
      },
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P99\",\"params\":[\"99\"],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"99\"]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"cbe69eb3-ac42-92fd-ab7d-5ff3e5248d80\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"437b8dd3-f199-2850-3232-88bffc708f1e\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"615e7058-d207-3a28-4d93-479eac66a8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"8c782231-bf2c-088b-dbcf-83d5923616ae\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} P99\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "P99", "name": "P99", "type": 3, "unit": "us" }
       ],
       "returnTags": [
        {
         "displayName": "time_1",
         "isResource": false,
         "name": "`time_1`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`server_node_type`",
         "role": "server"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`server_icon_id`",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_id_1",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_1",
         "role": "server"
        }
       ],
       "sql": "SELECT Percentile(`rrt`,0.99) AS `P99`, time(time, 1) AS `time_1`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND pod_ns_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_1`, auto_service_1, auto_service_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
      }
     ]
    },
    {
     "title": "Delay (by Consumer)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P90\",\"params\":[\"90\"],\"uuid\":\"1ca7fff4-5b4f-3983-d742-b067374660a1\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"eb0143cd-5999-d802-9d67-df5ece4c72f6\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"fb60194a-91c4-3eee-6b6e-9f2edb63db2d\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"2ba00600-db72-97eb-94b0-b18686df267e\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ab0edc8c-0f22-c791-543d-8f4e327ea43f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"8e7c1f83-9f0b-1d95-6477-e0a21b886e91\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"756a1bdb-c70e-6e6f-cfeb-f183bc378008\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8367d9fd-2126-7f0c-71a8-166f647a1d78\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"from\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b2f6bebe-15ee-14f3-888d-945414181cf0\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0} P90\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "P90", "name": "P90", "type": 3, "unit": "us" }
       ],
       "returnTags": [
        {
         "displayName": "time_60",
         "isResource": false,
         "name": "`time_60`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT Percentile(`rrt`,0.9) AS `P90`, time(time, 60) AS `time_60`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE auto_service_id_1!=0 AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND pod_ns_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, auto_instance_0, auto_instance_id_0, `client_node_type` SLIMIT 20 LIMIT 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Provider Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"error\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bc739c4a-597c-a766-4c84-16dd523873fd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ab2a1283-d767-268f-2065-d692846ec556\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"26e665a4-22a7-f01c-52de-9fd725f5fcff\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"b9a62f15-6f9b-d283-2ec7-cf4ce1fcaca1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "error", "name": "error", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "time_60",
         "isResource": false,
         "name": "`time_60`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`server_node_type`",
         "role": "server"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`server_icon_id`",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_id_1",
         "role": "server"
        },
        {
         "displayName": "Instance - K8s Service First",
         "isResource": true,
         "name": "auto_service_1",
         "role": "server"
        }
       ],
       "sql": "SELECT Sum(`server_error`) AS `error`, time(time, 60) AS `time_60`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM application_map WHERE auto_service_id_1!=0 AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND pod_ns_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, auto_service_1, auto_service_id_1, `server_node_type` SLIMIT 20 LIMIT 1000"
      }
     ]
    },
    {
     "title": "Consumer Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"error\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bc739c4a-597c-a766-4c84-16dd523873fd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"077aefc8-b15b-347d-df13-f12ba723fcf1\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"26e665a4-22a7-f01c-52de-9fd725f5fcff\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"cecbe1d1-6e47-05b9-e3e2-6e51eb820dc2\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"from\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "error", "name": "error", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "time_60",
         "isResource": false,
         "name": "`time_60`"
        },
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT Sum(`client_error`) AS `error`, time(time, 60) AS `time_60`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE auto_service_id_1!=0 AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND pod_ns_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, auto_instance_0, auto_instance_id_0, `client_node_type` SLIMIT 20 LIMIT 1000"
      }
     ]
    },
    {
     "title": "Server Error (by Consumer)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"server_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4cf72c15-65ea-d22d-907f-f81ce868e3f0\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3b4ff-8928-db85-4161-aeb137b33cba\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6d91ce00-51bc-0c00-cef7-e13cd8e6088b\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f5b5beb3-c7e6-9b2c-04a9-f68ce9cfc5bb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"client_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "server_error", "name": "server_error", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT Sum(`server_error`) AS `server_error`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE l7_protocol IN (40) AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND pod_ns_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_instance_0, auto_instance_id_0, `client_node_type` ORDER BY `server_error` desc LIMIT 10"
      }
     ]
    },
    {
     "title": "Client Error (by Consumer)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"client_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4cf72c15-65ea-d22d-907f-f81ce868e3f0\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3b4ff-8928-db85-4161-aeb137b33cba\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"11198591-5d70-8399-2f2d-59c1e8a57b15\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f5b5beb3-c7e6-9b2c-04a9-f68ce9cfc5bb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "client_error", "name": "client_error", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT Sum(`client_error`) AS `client_error`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE l7_protocol IN (40) AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND pod_ns_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_instance_0, auto_instance_id_0, `client_node_type` ORDER BY `client_error` desc LIMIT 10"
      }
     ]
    },
    {
     "title": "Time Out (by Consumer)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"time_out\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4cf72c15-65ea-d22d-907f-f81ce868e3f0\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3b4ff-8928-db85-4161-aeb137b33cba\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5cb559af-8ad5-a434-103e-6eb4bddc9bde\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f5b5beb3-c7e6-9b2c-04a9-f68ce9cfc5bb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"client_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "time_out", "name": "time_out", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "节点类型",
         "isResource": true,
         "name": "`client_node_type`",
         "role": "client"
        },
        {
         "displayName": "图标",
         "isResource": true,
         "name": "`client_icon_id`",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_id_0",
         "role": "client"
        },
        {
         "displayName": "Instance - K8s POD First",
         "isResource": true,
         "name": "auto_instance_0",
         "role": "client"
        }
       ],
       "sql": "SELECT Sum(`timeout`) AS `time_out`, node_type(auto_instance_0) AS `client_node_type`, icon_id(auto_instance_0) AS `client_icon_id`, auto_instance_id_0, auto_instance_0 FROM application_map WHERE l7_protocol IN (40) AND pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND pod_ns_id_1!=0 AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY auto_instance_0, auto_instance_id_0, `client_node_type` ORDER BY `time_out` desc LIMIT 10"
      }
     ]
    },
    {
     "title": "Error (by Error Message)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "_comment": "Please DON'T modify this variable selection field.",
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"response_code\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Code\",\"params\":[],\"uuid\":\"555b1219-0655-a006-d254-6423bcd1501f\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Message\",\"params\":[],\"uuid\":\"eb51c26b-c788-fb4c-612e-6b902e51c41f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"Log Count\",\"params\":[],\"uuid\":\"25038ea5-c8ff-134a-bdd3-5158123f881c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"1cfacf8b-ea30-6085-d5c1-52a6a139e1f2\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0ed4d8dd-5af6-81ce-c6c6-3db80073dfbf\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"30450b20-4744-2ca1-db74-1114c7573d6e\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"0d7570e3-1ea3-03c0-be9b-74c6f1019131\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_code\",\"func\":\"\",\"op\":\"NOT IN\",\"val\":[{\"value\":\"20\",\"label\":\"20\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4efc6a42-30e1-a772-0661-71b64b5422fa\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0dbf0a6f-fdc9-eaa2-8e15-3f66d0c3db6f\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"response_code\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a8ac2e39-8376-c5be-0d4d-edcad88095cd\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"209fc956-eedd-c4ed-3194-f06f2ee4736c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e9f33a34-e322-2732-ce3d-3dc30397c5b0\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"25038ea5-c8ff-134a-bdd3-5158123f881c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"Log Count\",\"showMetrics\":-1,\"tracingId\":null}",
       "returnMetrics": [
        { "displayName": "Log Count", "name": "Log Count", "type": 1, "unit": "" }
       ],
       "returnTags": [
        {
         "displayName": "Code",
         "isResource": false,
         "name": "`Code`"
        },
        {
         "displayName": "Message",
         "isResource": false,
         "name": "`Message`"
        },
        {
         "displayName": "Response Code",
         "isResource": false,
         "name": "response_code"
        },
        {
         "displayName": "Response Exception",
         "isResource": false,
         "name": "response_exception"
        }
       ],
       "sql": "SELECT Sum(`log_count`) AS `Log Count`, response_code AS `Code`, response_exception AS `Message` FROM l7_flow_log WHERE pod_cluster_id_1!=0 AND pod_ns_id_1!=0 AND auto_service_id_1!=0 AND l7_protocol IN (40) AND response_code NOT IN (20) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `Code`, `Message` ORDER BY `Log Count` desc LIMIT 100"
      }
     ]
    }
   ]
  },
  { "title": "Request Log Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TopN Request by Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7af09110-f5d4-ab07-4490-9817e27ca559\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"98046797-4314-dd6a-fdab-1db7d246e39b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7388f0c5-2749-57d3-7873-5fea6a741162\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"a3c928f4-ec3f-aeb8-4bc7-858291941e3e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"ee0242ef-19a2-26aa-6834-7210aeab9022\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2fe272ca-2ded-11fa-e05c-aa2cbf15c1dd\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91122c7e-c788-97e0-f559-894b94b2e2ce\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ac26e4f4-bd7f-9815-ad1e-e27eafd71eba\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7af09110-f5d4-ab07-4490-9817e27ca559\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(log_count)", "name": "Sum(log_count)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "API Endpoint",
       "isResource": false,
       "name": "endpoint"
      }
     ],
     "sql": "SELECT Sum(`log_count`) AS `Sum(log_count)`, endpoint FROM l7_flow_log WHERE pod_cluster_id_1!=0 AND auto_service_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY endpoint ORDER BY `Sum(log_count)` desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Provider Request Log",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5428ded0-b575-c40e-f585-026a4338e12b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"where\":[{\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"98046797-4314-dd6a-fdab-1db7d246e39b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"2515b825-8d8a-3761-8cd3-8c374cb9587a\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c85e7a93-3c3b-51f1-0345-2d2d64c9ceec\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"5bb82529-ffe5-5c39-7b0f-3265859ba8d7\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2fe272ca-2ded-11fa-e05c-aa2cbf15c1dd\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a11d4dc3-8c39-1c9c-b885-a1d3fe03ffcf\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ac26e4f4-bd7f-9815-ad1e-e27eafd71eba\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"60\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(log_count)", "name": "Sum(log_count)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_60",
       "isResource": false,
       "name": "`time_60`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      }
     ],
     "sql": "SELECT Sum(`log_count`) AS `Sum(log_count)`, time(time, 60) AS `time_60`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, auto_service_id_1, auto_service_1 FROM l7_flow_log WHERE pod_cluster_1 = 'k8s-d-5Us8Lds7Co' AND auto_service_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_60`, auto_service_1, auto_service_id_1, `server_node_type` ORDER BY `Sum(log_count)` desc SLIMIT 20 LIMIT 100"
    }
   ]
  },
  {
   "title": "Distributed Tracing (>=100ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"appTracing\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4b03920f-68bf-84e6-989a-023c0a983546\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_instance_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"295380d3-c64d-9305-ac84-57c50c39e74a\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"Tap Side\",\"params\":[],\"uuid\":\"e520efef-cc99-1bcc-ff98-3e57c520c075\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Enum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Method\",\"params\":[],\"uuid\":\"98f579bd-ac4d-8f3e-15a4-4a2d62dcc1d1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cbb6c14d-6766-3900-519d-f35d303c3b6c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"Status\",\"params\":[],\"uuid\":\"5578a571-0b67-b538-27e4-daae4f01259f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"start_time\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Start Time\",\"params\":[],\"uuid\":\"beaaf242-d180-dcd2-e952-6eca4e5f62a3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"where\":[{\"type\":\"tag\",\"key\":\"capture_nic_type\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"eBPF\",\"value\":7},{\"label\":\"OTel\",\"value\":8}],\"as\":\"\",\"params\":[],\"uuid\":\"1e9bce7f-5590-cc71-65ad-c779e3127d60\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b79356a7-5ba7-12d0-6c6c-f4fca2bc307b\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"a2f5bdc1-4054-4609-5320-90bbb3003df6\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$service\",\"value\":\"service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3cce1372-7eae-7c8c-a380-eb179ec65bf6\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Dubbo\",\"value\":40}],\"as\":\"\",\"params\":[],\"uuid\":\"fa4435ac-0e07-75fc-82f4-c910b3881d93\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"fromSelectcc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"func\":\"\",\"op\":\">=\",\"val\":\"100000\",\"as\":\"\",\"params\":[],\"uuid\":\"da18d4b6-9bc6-4019-e684-08ea89d3fcdc\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}}],\"groupBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d04b2ee1-c8a2-6348-cb7e-59f179cc4011\",\"type\":\"tag\"}],\"orderBy\":[{\"key\":\"fromSelectcc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"477e97ad-c61c-46ed-c321-f94c72e0fd7e\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Response Delay", "name": "Response Delay", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s POD First",
       "isResource": true,
       "name": "auto_instance_0",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s POD First",
       "isResource": true,
       "name": "auto_instance_1",
       "role": "server"
      },
      {
       "displayName": "Tap Side",
       "isResource": false,
       "name": "`Tap Side`"
      },
      {
       "displayName": "Method",
       "isResource": false,
       "name": "`Method`"
      },
      {
       "displayName": "Request Resource",
       "isResource": false,
       "name": "request_resource"
      },
      {
       "displayName": "Status",
       "isResource": false,
       "name": "`Status`"
      },
      {
       "displayName": "Start Time",
       "isResource": false,
       "name": "`Start Time`"
      },
      {
       "displayName": "UID",
       "isResource": false,
       "name": "toString(_id)"
      },
      {
       "displayName": "Instance - K8s POD First",
       "isResource": true,
       "name": "auto_instance_id_0",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s POD First",
       "isResource": true,
       "name": "auto_instance_id_1",
       "role": "server"
      }
     ],
     "sql": "SELECT `response_duration` AS `Response Delay`, auto_instance_0, auto_instance_1, Enum(observation_point) AS `Tap Side`, request_type AS `Method`, request_resource, Enum(response_status) AS `Status`, toString(start_time) AS `Start Time`, toString(_id), auto_instance_id_0, auto_instance_id_1 FROM l7_flow_log WHERE capture_nic_type IN (7,8) AND pod_cluster_id_1!=0 AND pod_ns_id_1!=0 AND auto_service_id_1!=0 AND l7_protocol IN (40) AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' and `response_duration`>='100000' ORDER BY `Response Delay` desc LIMIT 1000"
    }
   ]
  },
  {
   "type": "khulnasoft-tracing-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "queryText": "{\"appType\":\"appTracingFlame\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"187e7913-b779-5f0a-7c91-ac92e618e76c\",\"type\":\"metric\"}],\"where\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"777737e0-25f9-2e22-9430-82e29583a95b\",\"type\":\"tag\"}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e95ab83a-a3a1-9a4f-aaf3-574e52db07d9\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9fc585e0-434d-7f77-d293-954a62804138\",\"type\":\"tag\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"05646e38-adc6-5802-0493-88ca5dbf6b36\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":{\"label\":\"$khulnasoft_tracing_id\",\"value\":\"$khulnasoft_tracing_id\",\"isVariable\":true,\"variableType\":\"textbox\"}}"
    }
   ]
  }
 ]
}