{
 "title": "KhulnaSoft Server - Ingester",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "khulnasoft-khulnasoft-datasource"
   },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Write ClickHouse (+success/-failed)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_ckwriter\",\"select\":[{\"type\":\"metric\",\"key\":\"metrics.write_success_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"success\",\"params\":[],\"uuid\":\"d490d2e5-f0a2-2900-9c89-4662e1fcd082\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.write_failed_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"failed\",\"params\":[],\"uuid\":\"3bbb62eb-11a3-f1e1-7d49-363ad988feab\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"type\":\"tag\",\"key\":\"tag.table\",\"func\":\"\",\"op\":\"NOT REGEXP\",\"val\":\"flow_tag-.*\",\"as\":\"\",\"params\":[],\"uuid\":\"b15e6228-2876-bbee-4285-0b8cf1d00c4a\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"12b4818d-8231-fe0a-a747-d8bc04d2aa5e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f696ed6a-4326-9ea4-c2c5-a13dcf06844a\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a2e954f3-f040-5020-cd8c-850c074eeb7e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.table\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"31dac46a-2706-33cb-05ce-87ad8f8a048c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"51b1cb00-baf2-87d7-b9e6-8771de09c13f\",\"sort\":\"asc\"}],\"interval\":\"10\",\"slimit\":\"100\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.table} write-\",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "success", "name": "success", "type": 1, "unit": "" },
      { "displayName": "failed", "name": "failed", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_10",
       "isResource": false,
       "name": "`time_10`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.table",
       "isResource": false,
       "name": "tag.table"
      }
     ],
     "sql": "SELECT (Sum(`metrics.write_success_count`)/10) AS `success`, (Sum(`metrics.write_failed_count`)/10) AS `failed`, time(time, 10) AS `time_10`, `tag.host`, `tag.table` FROM `khulnasoft_server_ingester_ckwriter` WHERE `tag.table` NOT REGEXP 'flow_tag-.*' AND `tag.host` IN ('node1') AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_10`, `tag.host`, `tag.table` SLIMIT 100 LIMIT 10000"
    }
   ]
  },
  {
   "title": "Queue(+in/-out) ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_queue\",\"select\":[{\"key\":\"metrics.in\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"in\",\"params\":[],\"uuid\":\"f95c6ffb-5bff-73d9-70d9-d3eb6b931906\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.out\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"out\",\"params\":[],\"uuid\":\"72e5b798-6675-9d2a-6ae8-a59e7926e453\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.module\",\"func\":\"\",\"op\":\"NOT REGEXP\",\"val\":\"flow_tag-.*\",\"as\":\"\",\"params\":[],\"uuid\":\"50aefbf8-1f70-453b-f032-f72223bccfd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.module\",\"func\":\"\",\"op\":\"NOT REGEXP\",\"val\":\"khulnasoft_admin-.*\",\"as\":\"\",\"params\":[],\"uuid\":\"ce0e75c0-4d7c-d6d9-3cc5-a7b9e00e897f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"72f67a46-8abf-bb93-0c65-a55153c22dfe\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"be071ad7-44d2-e477-58be-a75d682d076a\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"92efbae9-00e3-95c6-b7d3-310d6c8219d2\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.module\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3cb627be-741d-bb14-20ce-19e30e801fc5\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d09b61de-4abf-0367-27a9-f11c1062366f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"slimit\":\"100\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.module} \",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "in", "name": "in", "type": 1, "unit": "" },
      { "displayName": "out", "name": "out", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_10",
       "isResource": false,
       "name": "`time_10`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.module",
       "isResource": false,
       "name": "tag.module"
      }
     ],
     "sql": "SELECT (Sum(`metrics.in`)/10) AS `in`, (Sum(`metrics.out`)/10) AS `out`, time(time, 10) AS `time_10`, `tag.host`, `tag.module` FROM `khulnasoft_server_ingester_queue` WHERE `tag.module` NOT REGEXP 'flow_tag-.*' AND `tag.module` NOT REGEXP 'khulnasoft_admin-.*' AND `tag.host` IN ('node1','node2') AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_10`, `tag.host`, `tag.module` SLIMIT 100 LIMIT 10000"
    }
   ]
  },
  {
   "title": "Queue(+pending/-drop) ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_queue\",\"select\":[{\"key\":\"metrics.pending\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"pending\",\"params\":[],\"uuid\":\"f95c6ffb-5bff-73d9-70d9-d3eb6b931906\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.overwritten\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"drop\",\"params\":[],\"uuid\":\"b938ea99-579e-ad19-8257-927f17053532\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.module\",\"func\":\"\",\"op\":\"NOT REGEXP\",\"val\":\"flow_tag-.*\",\"as\":\"\",\"params\":[],\"uuid\":\"50aefbf8-1f70-453b-f032-f72223bccfd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.module\",\"func\":\"\",\"op\":\"NOT REGEXP\",\"val\":\"khulnasoft_admin-.*\",\"as\":\"\",\"params\":[],\"uuid\":\"ce0e75c0-4d7c-d6d9-3cc5-a7b9e00e897f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"036de4d5-03c5-5f35-ad13-8a07699f69a1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7298fb1b-f3cf-f5b5-2ba4-3eaf6a5663a8\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"92efbae9-00e3-95c6-b7d3-310d6c8219d2\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.module\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3cb627be-741d-bb14-20ce-19e30e801fc5\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d09b61de-4abf-0367-27a9-f11c1062366f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"slimit\":\"100\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.module} \",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "pending", "name": "pending", "type": 1, "unit": "" },
      { "displayName": "drop", "name": "drop", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_10",
       "isResource": false,
       "name": "`time_10`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.module",
       "isResource": false,
       "name": "tag.module"
      }
     ],
     "sql": "SELECT (Sum(`metrics.pending`)/10) AS `pending`, (Sum(`metrics.overwritten`)/10) AS `drop`, time(time, 10) AS `time_10`, `tag.host`, `tag.module` FROM `khulnasoft_server_ingester_queue` WHERE `tag.module` NOT REGEXP 'flow_tag-.*' AND `tag.module` NOT REGEXP 'khulnasoft_admin-.*' AND `tag.host` IN ('node1') AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_10`, `tag.host`, `tag.module` SLIMIT 100 LIMIT 10000"
    }
   ]
  },
  {
   "title": "flow log(in) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_decoder\",\"select\":[{\"key\":\"metrics.count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"in\",\"params\":[],\"uuid\":\"18852661-6d75-03a9-9b5d-e199b933829d\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9c0d5b3d-d817-19ce-85ee-ccf5e4656956\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"51f516df-303c-7c54-7cd3-465d26d78dbe\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6e513212-6c4c-68ce-de27-831e8dd2822c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.msg_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ed7aa66d-9597-b615-e281-358ba0c08c23\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"52cb8a8f-611b-19df-3bd4-aeed6e18fc0c\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.msg_type}\",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "in", "name": "in", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_10",
       "isResource": false,
       "name": "`time_10`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.msg_type",
       "isResource": false,
       "name": "tag.msg_type"
      }
     ],
     "sql": "SELECT (Sum(`metrics.count`)/10) AS `in`, time(time, 10) AS `time_10`, `tag.host`, `tag.msg_type` FROM `khulnasoft_server_ingester_decoder` WHERE `tag.host` IN ('node2','node1') AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_10`, `tag.host`, `tag.msg_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "flow log(throttle-drop) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_decoder\",\"select\":[{\"key\":\"metrics.drop_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"drop\",\"params\":[],\"uuid\":\"18852661-6d75-03a9-9b5d-e199b933829d\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9c0d5b3d-d817-19ce-85ee-ccf5e4656956\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"814f6869-1ff3-da46-f888-a654e23a14d4\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6e513212-6c4c-68ce-de27-831e8dd2822c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.msg_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d74b76e0-ba2b-6a10-54fe-8d1ac2a0eb55\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"52cb8a8f-611b-19df-3bd4-aeed6e18fc0c\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.msg_type}\",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "drop", "name": "drop", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_10",
       "isResource": false,
       "name": "`time_10`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.msg_type",
       "isResource": false,
       "name": "tag.msg_type"
      }
     ],
     "sql": "SELECT (Sum(`metrics.drop_count`)/10) AS `drop`, time(time, 10) AS `time_10`, `tag.host`, `tag.msg_type` FROM `khulnasoft_server_ingester_decoder` WHERE `tag.host` IN ('node2','node1') AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_10`, `tag.host`, `tag.msg_type` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "flow metrics(in) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_unmarshaller\",\"select\":[{\"key\":\"metrics.network\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"port\",\"params\":[],\"uuid\":\"f95c6ffb-5bff-73d9-70d9-d3eb6b931906\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.network_1s\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"port-1s\",\"params\":[],\"uuid\":\"c049c5fd-cc33-21c1-c2e4-890b3e1cb999\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.network_map\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"edge-port\",\"params\":[],\"uuid\":\"0e59f70b-a885-e3fd-5229-9b480535b5c2\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.network_map_1s\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"edge-port-1s\",\"params\":[],\"uuid\":\"d5363081-f101-8bf3-ff58-369519a137bd\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.traffic_policy\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"acl\",\"params\":[],\"uuid\":\"08d26cef-34b4-6cdf-27b2-1cbf2a9b4612\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":1}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":1}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"50aefbf8-1f70-453b-f032-f72223bccfd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d042ee1b-a589-ab20-a2f2-dbb072af75bc\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"92efbae9-00e3-95c6-b7d3-310d6c8219d2\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d09b61de-4abf-0367-27a9-f11c1062366f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} in-\",\"showMetrics\":1,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "flow metrics(other) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_unmarshaller\",\"select\":[{\"key\":\"metrics.drop_doc_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"drop-dis-region\",\"params\":[],\"uuid\":\"f95c6ffb-5bff-73d9-70d9-d3eb6b931906\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.err_doc_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"error\",\"params\":[],\"uuid\":\"85ed310c-268a-2ec1-62e9-3c9984ea2f10\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.future_doc_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"future\",\"params\":[],\"uuid\":\"eb523541-0fd7-95d5-4735-8c3108c8a5ea\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.expired_doc_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"expired\",\"params\":[],\"uuid\":\"ddab7f18-861f-bd5b-4997-5a622fbe3dd4\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"50aefbf8-1f70-453b-f032-f72223bccfd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3a68b081-1f41-0479-2ebb-8fff5b5dead9\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"92efbae9-00e3-95c6-b7d3-310d6c8219d2\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d09b61de-4abf-0367-27a9-f11c1062366f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} other-\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "drop-dis-region", "name": "drop-dis-region", "type": 1, "unit": "" },
      { "displayName": "error", "name": "error", "type": 1, "unit": "" },
      { "displayName": "future", "name": "future", "type": 1, "unit": "" },
      { "displayName": "expired", "name": "expired", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_10",
       "isResource": false,
       "name": "`time_10`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT (Sum(`metrics.drop_doc_count`)/10) AS `drop-dis-region`, (Sum(`metrics.err_doc_count`)/10) AS `error`, (Sum(`metrics.future_doc_count`)/10) AS `future`, (Sum(`metrics.expired_doc_count`)/10) AS `expired`, time(time, 10) AS `time_10`, `tag.host` FROM `khulnasoft_server_ingester_unmarshaller` WHERE `tag.host` IN ('node2','node1') AND time>='${__from:date:seconds}' AND time<='${__to:date:seconds}' GROUP BY `time_10`, `tag.host` SLIMIT 20 LIMIT 1000"
    }
   ]
  },
  {
   "title": "ext metrics(+in/-out) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_decoder\",\"select\":[{\"key\":\"metrics.in_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"in\",\"params\":[],\"uuid\":\"f24cb055-1cd2-a044-47f3-077e4dbe40bf\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.out_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"out\",\"params\":[],\"uuid\":\"e58c0d1b-8e7e-0a4a-de12-f4f327a9e791\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"08a29eb3-dda2-8493-65c9-b0b3eeb51796\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"11d819d1-090c-f094-192e-f0cc4a1ed0c8\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9044b0a4-6d16-e450-44d2-a8d0226773e4\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.msg_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a6314775-db1e-0a11-5a20-2605a68d1069\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"961007c2-cc0a-74a9-df8f-c24c6951f72e\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.msg_type} \"}"
    }
   ]
  },
  {
   "title": "ext metrics(other) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_decoder\",\"select\":[{\"key\":\"metrics.drop_unsupported_metrics\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"unsupport-metrics-total\",\"params\":[],\"uuid\":\"f24cb055-1cd2-a044-47f3-077e4dbe40bf\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.err_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"err-decode\",\"params\":[],\"uuid\":\"8fbd5590-bb70-23b0-df62-465401085cba\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}},{\"type\":\"metric\",\"key\":\"metrics.err_metrics\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"err-metrics\",\"params\":[],\"uuid\":\"a9f9047a-d510-72bd-805e-29ab052e64a7\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"08a29eb3-dda2-8493-65c9-b0b3eeb51796\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"11d819d1-090c-f094-192e-f0cc4a1ed0c8\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9044b0a4-6d16-e450-44d2-a8d0226773e4\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.msg_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a6314775-db1e-0a11-5a20-2605a68d1069\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"961007c2-cc0a-74a9-df8f-c24c6951f72e\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.msg_type}\",\"showMetrics\":1,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_pool\",\"select\":[{\"key\":\"metrics.in_use_objects\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"in-use-count\",\"params\":[],\"uuid\":\"5c77c831-6eaf-6c64-b1c1-081649f54de3\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"261c7d99-b536-615d-cd0b-189af7304bc7\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ee0cb1ae-4177-9677-69d7-cdbe9344bd08\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8689b56a-1a62-965f-8b16-c9eb9ccdb5fb\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.name\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"49f42176-1bc4-f9bd-c52c-ef06b4a5d7dc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"595f7308-6c25-9dd2-b952-b3dd4e9bbcb6\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"limit\":\"30000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.name}\",\"showMetrics\":1,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "platformData",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_platformdata\",\"select\":[{\"key\":\"metrics.grpc_request_time\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"request\",\"params\":[],\"uuid\":\"8941753e-c3b5-a386-22f6-9e0fc9b06012\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"metrics.update_platform_time\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"platform\",\"params\":[],\"uuid\":\"6588848d-ef7e-97fe-dc11-c60e33b61f85\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"metrics.update_service_time\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"service\",\"params\":[],\"uuid\":\"206fc082-79f1-218c-e2cd-dc744f308d08\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f42e9b23-e449-afb7-cd76-4ee2167720ce\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b269c5ea-fb2c-087e-b0ce-910e87001d5c\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3e46c170-19f5-1829-c8c1-3e396d82052c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"1cbc89df-8116-d2f4-c66a-e6350705dac1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"10\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":1,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "metrics-decode-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_unmarshaller\",\"select\":[{\"key\":\"metrics.avg_time\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"avg_time\",\"params\":[],\"uuid\":\"72f84f1e-e99b-3525-c7f6-dab5d5566555\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"metrics.total_time\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"total-time\",\"params\":[],\"uuid\":\"5a67f2bd-1a7d-a221-c85a-1fdee05513aa\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f4b0eb6f-3a38-aef4-4243-2649e746133e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fdaec7f-46b7-0177-fb19-6369074452dc\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"63c3121b-6c2b-8246-6066-5b625933dcd3\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c46ee6ff-ae34-60ad-35c5-ac790e14bb93\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host}\",\"showMetrics\":1,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "flow-log-decode-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_ingester_decoder\",\"select\":[{\"key\":\"metrics.avg_time\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"avg-time\",\"params\":[],\"uuid\":\"72f84f1e-e99b-3525-c7f6-dab5d5566555\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"metrics.total_time\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"total-time\",\"params\":[],\"uuid\":\"691957f9-4921-a117-3cd7-a15553a87675\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f4b0eb6f-3a38-aef4-4243-2649e746133e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"fromSelect72f84f1e-e99b-3525-c7f6-dab5d5566555\",\"func\":\"Avg\",\"op\":\">=\",\"val\":\"0\",\"as\":\"\",\"params\":[],\"uuid\":\"3fdaec7f-46b7-0177-fb19-6369074452dc\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"metrics.avg_time\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"avg-time\",\"params\":[],\"uuid\":\"72f84f1e-e99b-3525-c7f6-dab5d5566555\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"63c3121b-6c2b-8246-6066-5b625933dcd3\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.msg_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7c952e7b-5d63-c3dd-116d-1874fdc6b075\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c46ee6ff-ae34-60ad-35c5-ac790e14bb93\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} ${tag.msg_type}\",\"showMetrics\":1,\"tracingId\":null}"
    }
   ]
  }
 ]
}