{
 "title": "KhulnaSoft Server - Querier",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "khulnasoft-khulnasoft-datasource"
   },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Avg Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_count\",\"select\":[{\"key\":\"metrics.query_time_avg\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"ck_avg\",\"params\":[],\"uuid\":\"6327083a-d127-d395-a2ad-1cf8150d3121\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"metric\",\"key\":\"metrics.api_time_avg\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"api_avg\",\"params\":[],\"uuid\":\"484bce3a-9f42-600b-f8f9-bd4a2d013ed0\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0c9341d7-e471-057c-d893-96cf4fb9653b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5909c9a6-1e16-371f-f41a-d0bbe30823a5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"30163f63-8bd9-4b01-52f5-219761f96c50\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fb4b98e-0976-9465-f8e5-637cfd00f893\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "ck_avg", "name": "ck_avg", "type": 1, "unit": "" },
      { "displayName": "api_avg", "name": "api_avg", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT Avg(`metrics.query_time_avg`) AS `ck_avg`, Avg(`metrics.api_time_avg`) AS `api_avg`, time(time, $__interval) AS `time_$__interval`, `tag.host` FROM `khulnasoft_server_querier_querier_count` WHERE `tag.host` IN ('prometheus-benchmark-test002','prometheus-benchmark-test001') AND time>='1686290210' AND time<='1686293810' GROUP BY `time_$__interval`, `tag.host` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "Max Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_count\",\"select\":[{\"type\":\"metric\",\"key\":\"metrics.query_time_max\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"ck_max\",\"params\":[],\"uuid\":\"00820176-d66e-ec1f-d65b-7a6b043b6743\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"metrics.api_time_max\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"api_max\",\"params\":[],\"uuid\":\"0c21c652-20e6-88a0-1ae9-5e1fccd55c48\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0c9341d7-e471-057c-d893-96cf4fb9653b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7e639fd8-73b8-0816-101d-33e4b9389388\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"30163f63-8bd9-4b01-52f5-219761f96c50\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fb4b98e-0976-9465-f8e5-637cfd00f893\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "ck_max", "name": "ck_max", "type": 1, "unit": "" },
      { "displayName": "api_max", "name": "api_max", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT Max(`metrics.query_time_max`) AS `ck_max`, Max(`metrics.api_time_max`) AS `api_max`, time(time, $__interval) AS `time_$__interval`, `tag.host` FROM `khulnasoft_server_querier_querier_count` WHERE `tag.host` IN ('prometheus-benchmark-test002','prometheus-benchmark-test001') AND time>='1686290233' AND time<='1686293833' GROUP BY `time_$__interval`, `tag.host` SLIMIT 20 LIMIT 10000"
    }
   ]
  },
  {
   "title": "Avg API Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_api_count\",\"select\":[{\"type\":\"metric\",\"key\":\"metrics.api_time_avg\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"api_avg\",\"params\":[],\"uuid\":\"f4cc022e-2ad6-d6f4-3f7c-4a54542df546\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6584378e-a3c5-b237-cb39-dd4d73440fad\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7515c0d9-b4e1-5cba-247f-8bbe0f362f59\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.path\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4d819a69-0035-1543-f8f1-eb40458b71f0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4e078ccd-4be8-f6be-fa59-47af243e44da\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.method\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"1133bdfc-cb20-222e-751c-852e088e0405\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9b1086a9-add4-4b6e-25b8-a9870bd80932\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} - ${tag.method}-${tag.path}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "api_avg", "name": "api_avg", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.path",
       "isResource": false,
       "name": "tag.path"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.method",
       "isResource": false,
       "name": "tag.method"
      }
     ],
     "sql": "SELECT Avg(`metrics.api_time_avg`) AS `api_avg`, time(time, $__interval) AS `time_$__interval`, `tag.path`, `tag.host`, `tag.method` FROM `khulnasoft_server_querier_querier_api_count` WHERE `tag.host` IN ('ubuntu-12') AND time>='1689319674' AND time<='1689323274' GROUP BY `time_$__interval`, `tag.path`, `tag.host`, `tag.method` SLIMIT 20 LIMIT 100"
    }
   ]
  },
  {
   "title": "Api Usage Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_api_count\",\"select\":[{\"key\":\"metrics.api_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"api_sum\",\"params\":[],\"uuid\":\"d187b088-6e76-5483-065b-861f1dcc65a5\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6584378e-a3c5-b237-cb39-dd4d73440fad\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"1527666f-c027-7623-b027-34e757193349\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4d819a69-0035-1543-f8f1-eb40458b71f0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.method\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7044be19-36c2-66f2-0777-2fa75470ecc9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.path\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"bd27ace5-63bc-b19a-c126-6cea0f5cd960\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9b1086a9-add4-4b6e-25b8-a9870bd80932\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]},\"fromSelect\":{\"key\":\"metrics.api_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"api_sum\",\"params\":[],\"uuid\":\"d187b088-6e76-5483-065b-861f1dcc65a5\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"${tag.host}.${tag.method}-${tag.path}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "api_sum", "name": "api_sum", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      },
      {
       "displayName": "tag.method",
       "isResource": false,
       "name": "tag.method"
      },
      {
       "displayName": "tag.path",
       "isResource": false,
       "name": "tag.path"
      }
     ],
     "sql": "SELECT Sum(`metrics.api_count`) AS `api_sum`, `tag.host`, `tag.method`, `tag.path` FROM `khulnasoft_server_querier_querier_api_count` WHERE `tag.host` IN ('ubuntu-12') AND time>='1689320759' AND time<='1689324359' GROUP BY `tag.host`, `tag.method`, `tag.path` ORDER BY `api_sum` desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Query Rate (requests/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_count\",\"select\":[{\"type\":\"metric\",\"key\":\"metrics.query_count\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"query_count\",\"params\":[],\"uuid\":\"e6faf8ea-eb23-8446-cf66-ceb196c7b37f\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}},{\"type\":\"metric\",\"key\":\"metrics.api_count\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"api_count\",\"params\":[],\"uuid\":\"73178ea3-a092-ec1d-ac8c-8129a6e55da5\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f2710ab5-b7f1-3857-5d9a-e67254558e8b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"22f930eb-e8b8-6d07-214f-dbeffab3bfc8\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91902828-01e3-64bb-722b-a0c8cfd75f28\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9f29049d-416b-f9a2-b5ac-133df189a5f7\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "query_count", "name": "query_count", "type": 1, "unit": "/s" },
      { "displayName": "api_count", "name": "api_count", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`metrics.query_count`)) AS `query_count`, PerSecond(Avg(`metrics.api_count`)) AS `api_count`, time(time, $__interval) AS `time_$__interval`, `tag.host` FROM `khulnasoft_server_querier_querier_count` WHERE `tag.host` IN ('prometheus-benchmark-test001') AND time>='1688023748' AND time<='1688027348' GROUP BY `time_$__interval`, `tag.host` SLIMIT 20 LIMIT 1000"
    }
   ]
  },
  {
   "title": "ClickHouse Response Rows (counts/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_count\",\"select\":[{\"type\":\"metric\",\"key\":\"metrics.row_count\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"row_count\",\"params\":[],\"uuid\":\"e6f62531-6d15-1b01-17f0-299a5533b4ed\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f2710ab5-b7f1-3857-5d9a-e67254558e8b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"511a7d43-15dd-f80f-3aaf-45dbdfae82af\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91902828-01e3-64bb-722b-a0c8cfd75f28\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9f29049d-416b-f9a2-b5ac-133df189a5f7\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "row_count", "name": "row_count", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT (Avg(`metrics.row_count`)/10) AS `row_count`, time(time, $__interval) AS `time_$__interval`, `tag.host` FROM `khulnasoft_server_querier_querier_count` WHERE `tag.host` IN ('prometheus-benchmark-test002','prometheus-benchmark-test001') AND time>='1686290272' AND time<='1686293872' GROUP BY `time_$__interval`, `tag.host` SLIMIT 20 LIMIT 1000"
    }
   ]
  },
  {
   "title": "ClickHouse Response Size (Byte/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_count\",\"select\":[{\"type\":\"metric\",\"key\":\"metrics.response_size\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"response_size\",\"params\":[],\"uuid\":\"4ecbc455-f453-4c6b-5ed7-088faee0648e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f2710ab5-b7f1-3857-5d9a-e67254558e8b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4b4daf80-a730-d85b-1b18-20f716da2b95\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91902828-01e3-64bb-722b-a0c8cfd75f28\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9f29049d-416b-f9a2-b5ac-133df189a5f7\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "response_size", "name": "response_size", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT Sum(`metrics.response_size`) AS `response_size`, time(time, $__interval) AS `time_$__interval`, `tag.host` FROM `khulnasoft_server_querier_querier_count` WHERE `tag.host` IN ('prometheus-benchmark-test002','prometheus-benchmark-test001') AND time>='1686290286' AND time<='1686293886' GROUP BY `time_$__interval`, `tag.host` SLIMIT 20 LIMIT 1000"
    }
   ]
  },
  {
   "title": "ClickHouse Response Columns (counts/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"khulnasoft_admin\",\"sources\":\"\",\"from\":\"khulnasoft_server_querier_querier_count\",\"select\":[{\"key\":\"metrics.column_count\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"column_count\",\"params\":[],\"uuid\":\"2dfb7276-27c4-5d27-86c0-432f61a6e5f6\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"Math\",\"op\":\"DIVIDE\",\"params\":10}]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f2710ab5-b7f1-3857-5d9a-e67254558e8b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"81ac5a1e-4392-7722-c0db-db02fccd92b8\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91902828-01e3-64bb-722b-a0c8cfd75f28\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9f29049d-416b-f9a2-b5ac-133df189a5f7\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${tag.host} \",\"showMetrics\":1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "column_count", "name": "column_count", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "time_$__interval",
       "isResource": false,
       "name": "`time_$__interval`"
      },
      {
       "displayName": "tag.host",
       "isResource": false,
       "name": "tag.host"
      }
     ],
     "sql": "SELECT (Avg(`metrics.column_count`)/10) AS `column_count`, time(time, $__interval) AS `time_$__interval`, `tag.host` FROM `khulnasoft_server_querier_querier_count` WHERE `tag.host` IN ('prometheus-benchmark-test002','prometheus-benchmark-test001') AND time>='1686290352' AND time<='1686293952' GROUP BY `time_$__interval`, `tag.host` SLIMIT 20 LIMIT 1000"
    }
   ]
  }
 ]
}